config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users, only: [:show, :index]
  
  resources :books do
    resources :schedules
    resources :lists
    resource :likes, only: [:create, :destroy]
    collection do
      get "search"
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :users
  belongs_to :book
  has_one_attached :image

  validates :category, :content, presence: true
  validates :quantity, inclusion: { in: 1..9999, allow_blank: true, message: "は 1～9999 の範囲で入力してください" }
  validates :price, inclusion: { in: 1..99999999, allow_blank: true, message: "は 1～99999999 の範囲で入力してください" }
  validates :quantity, :price, numericality: { only_integer: true, greater_than: 0, allow_blank: true, message: "は数値で入力してください" }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :book_find
  before_action :list_find, only: [:edit, :update, :destroy]
  before_action :category_find, except: :destroy

  def index
    @category = params[:category]
    @lists = @book.lists.where(category: @category)
    @content = @book.lists.distinct.pluck(:content)
  end

  def new
    @list = List.new
  end

  def create
    @list = @book.lists.new(list_params)
    if @list.save
      redirect_to book_lists_path(@book, category: @list.category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to book_lists_path(@book, category: @list.category)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to book_lists_path(@book, category: @list.category)
  end


  private
  def list_params
    params.require(:list)
    .permit(:image, :category, :content, :quantity, :price, :list_memo)
    .merge(user_id: current_user.id, book_id: params[:book_id])
  end

  def book_find
    @book = Book.find(params[:book_id])
  end

  def list_find
    @list = List.find(params[:id])
  end

  def category_find
    @categories = @book.lists.distinct.pluck(:category)
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<div class="form-set">
  <div class="form">
    カテゴリー<span>*</span>
  </div>
  <%= list.text_field :category, class:"f-category", placeholder:"10文字まで", maxlength:"10" %>
</div>
<div class="form-set">
  <div class="form">
    内容<span>*</span>
  </div>
  <%= list.text_field :content, class:"f-content", placeholder:"15文字まで", maxlength:"15" %>
</div>
<div class="form-set">
  <div class="form">
    数量
  </div>
  <%= list.text_field :quantity, class:"f-quantity" %>
</div>
<div class="form-set">
  <div class="form">
    金額
  </div>
  <%= list.text_field :price, class:"f-price" %>
</div>
<div class="form-set">
  <div class="form">
    メモ
  </div>
  <%= list.text_field :list_memo, class:"f-list_memo", placeholder:"30文字まで", maxlength:"30" %>
</div>
<div class="form-set">
  <div class="form">
    イメージ
  </div>
  <div class="upload">
    <%= list.file_field :image, class:"upload-btn"%>
  </div>
</div>
<div class="required">
  <span>*</span>は必須項目です
</div>

app/views/lists/edit.html.erb
<div class="tab">
  <div class="format">
    <div class="back">
      <%= link_to image_tag("back.png"), book_schedules_path %>
    </div>

    <%= form_with model: [@book, @list] do |list| %>
      <%= render "shared/error_messages", object: list.object %>
      <%= render "form", list: list %>

      <div class="form-set">
        <%= list.submit "変更", class:"submit-btn" %>
      </div>
      <div class="destroy">
        <div title="削除">
          <%= link_to image_tag("dustbin.png", class:"destroy-icon"), 
            book_list_path(@book, @list.id), data: { turbo_method: :delete }, method: :delete %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render "shared/tab" %>
</div>

app/views/lists/index.html.erb
<div class="tab">
  <div class="list">
    <div class="top">
      <%= @category %>
    </div>

    <div class="list-index">
      <% @lists.each do |list| %>
        <div class="lists">
          <div class="list-info">
            <%= link_to edit_book_list_path(list.book, list) do %>
              <div class="list-main">
              
                <div class="list-content">
                  <%= list.content %>
                </div>
              
                <% if list.quantity.present? %>
                  <div class="list-quantity">
                    数量　<%= list.quantity %>
                  </div>
                <% end %>
              </div>

              <div class="list-sub">
                <% if list.list_memo.present? %>
                  <div class="list-memo">
                    <%= list.list_memo %>
                  </div>
                <% end %>
                <% if list.price.present? %>
                  <div class="list-price">
                    金額　<%= list.price %>
                  </div>
                <% end %>
                <% if list.image.attached? %>
                  <%= image_tag list.image, class: "list-img" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%= render "shared/tab" %>
</div>

app/views/lists/new.html.erb
<div class="tab">
  <div class="format">
    <div class="back">
      <%= link_to image_tag("back.png"), book_schedules_path %>
    </div>

    <%= form_with(model: @list, url: book_lists_path(@book, @category)) do |list| %>
      <%= render "shared/error_messages", object: list.object %>
      <%= render "form", list: list %>

      <div class="form-set">
        <%= list.submit "追加", class:"submit-btn" %>
      </div>
    <% end %>
  </div>
  <%= render "shared/tab" %>
</div>