config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users, only: [:show, :index]
  
  resources :books do
    resources :schedules
    resources :lists
    resource :likes, only: [:create, :destroy]
    collection do
      get "search"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :schedules, dependent: :destroy
  has_many :lists, dependent: :destroy, through: :checks
  has_many :likes, dependent: :destroy

  validates :nickname, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: 'は半角英数を両方含む必要があります' }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @nickname = current_user.nickname
    @books = current_user.books.order(start: 'DESC')
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books.order(start: 'DESC')

    likes = Like.where(user_id: current_user.id).pluck(:book_id)  # ログイン中のユーザーのお気に入りのbook_idカラムを取得
    @like_list = Book.find(likes)     # booksテーブルから、お気に入り登録済みのレコードを取得
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="book">

  <div class="link-books">
    <div class="new-book">
      <%= link_to new_book_path do %>
        <%= image_tag "book.png", class: "new-book-icon" %>
        <span class="new-journey">New Journey</span>
      <% end %>
    </div>

    <div class="all-book">
      <%= link_to books_path do %>
        <%= image_tag "all-book.png", class: "all-book-icon" %>
        <span class="everyone">Everyone's Journey </span>
      <% end %>
    </div>
  </div>

  <div class="my-books">
    <%= link_to "My Journeys", "/", class:"my-journeys" %>
    <%= link_to "My favorite journeys", user_path(current_user), class:"my-favorite-journeys" %>
  </div>

  <div class="book-index">
    <% @books.each do |book| %>
      <%= render "books/book", book: book %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="book">

  <div class="link-books">
    <div class="new-book">
      <%= link_to new_book_path do %>
        <%= image_tag "book.png", class: "new-book-icon" %>
        <span class="new-journey">New Journey</span>
      <% end %>
    </div>

    <div class="all-book">
      <%= link_to books_path do %>
        <%= image_tag "all-book.png", class: "all-book-icon" %>
        <span class="everyone">Everyone's Journey </span>
      <% end %>
    </div>
  </div>

  <div class="my-books">
    <%= link_to "My Journeys", "/", class:"my-journeys" %>
    <%= link_to "My favorite journeys", users_path, class:"my-favorite-journeys" %>
  </div>

  <div class="book-index">
    <% @like_list.each do |book| %>
      <%= render "books/book", book: book %>
    <% end %>
  </div>
</div>