config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users, only: [:show, :index]
  
  resources :books do
    resources :schedules
    resources :lists
    resource :likes, only: [:create, :destroy]
    collection do
      get "search"
    end
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :users
  belongs_to :book
  has_many :locations, dependent: :destroy
  accepts_nested_attributes_for :locations, allow_destroy: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :icon

  has_one_attached :image

  validates :summary, :departure_time, presence: true
  validates :cost, inclusion: { in: 1..99999999, allow_blank: true, message: "は 1～99999999 の範囲で入力してください" }
  validates :cost, numericality: { only_integer: true, greater_than: 0, allow_blank: true, message: "は数値で入力してください" }

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :book_find
  before_action :schedule_find, only: [:edit, :update, :destroy]
  before_action :category_find, except: :destroy

  def index
    @schedules = @book.schedules.order(departure_time: 'ASC')
  end

  def new
    @schedule = Schedule.new
    @schedule.locations.build
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to book_schedules_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @schedule.locations.build
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to book_schedules_path(@schedule.book, @schedule)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @schedule.locations.destroy_all
    @schedule.destroy
    flash[:notice] = "削除が完了しました"
    redirect_to book_schedules_path
  end

  
  private
  def schedule_params
    params.require(:schedule)
    .permit(:image, :summary, :icon_id, :departure, :arrival,
        :departure_time, :arrival_time,:cost, :url, :url2, :memo,
      locations_attributes: [:id, :departure2, :arrival2,
        :departure_time2, :arrival_time2, :icon_id2, :_destroy])
    .merge(user_id: current_user.id, book_id: params[:book_id])
  end

  def book_find
    @book = Book.find(params[:book_id])
  end

  def schedule_find
    @schedule = Schedule.find(params[:id])
  end

  def category_find
    @categories = @book.lists.distinct.pluck(:category)
  end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<div class="form-set">
  <div class="form">
    タイトル<span>*</span>
  </div>
  <%= schedule.text_field :summary, class:"f-summary", placeholder:"20文字まで", maxlength:"20" %>
</div>

<div class="form-set">
  <div class="form">
    <%= schedule.label :icon_id, "アイコン" %>
    <div class="icon-select">
      <%= schedule.collection_radio_buttons :icon_id, Icon.all, :id, :image do |b| %>
        <div class="radio-label" onclick="selectIcon(this)">
          <%= b.label { image_tag(b.object.image, class: "s-icon", id: "icon_#{b.object.id}") } %>
        </div>
        <div class="icon-radio-btn">
          <%= b.radio_button %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="form-set">
  <div class="form">
    出発～到着
  </div>
  <div class="f-d-a">
    <%= schedule.datetime_field :departure_time, class:"period" %>
    <span>*</span>～
    <%= schedule.datetime_field :arrival_time, class:"period" %>
  </div>
  <div class="f-d-a">
    <%= schedule.text_field :departure, class:"f-departure", placeholder:"出発地" %>
    ～
    <%= schedule.text_field :arrival, class:"f-arrival", placeholder:"到着地" %>
  </div>
</div>


<div class="add-menus-container" id="add-menus">
  <div class="add-menu" style="display: none;">
    <%= schedule.fields_for :locations do |location| %>
      <div class="form-set">
        <div class="form">
          <%= location.label :icon_id, "アイコン" %>
          <div class="icon-select">
            <%= location.collection_radio_buttons :icon_id, Icon.all, :id, :image do |b| %>
              <div class="radio-label" onclick="selectIcon(this)">
                <%= b.label { image_tag(b.object.image, class: "f-icon", id: "icon_#{b.object.id}") } %>
              </div>
              <div class="icon-radio-btn">
                <%= b.radio_button %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="form-set">
        <div class="form">
          出発～到着
        </div>
        <div class="f-d-a">
          <%= location.datetime_field :departure_time2, class:"period" %>
          ～
          <%= location.datetime_field :arrival_time2, class:"period" %>
        </div>
        <div class="f-d-a">
          <%= location.text_field :departure2, class:"f-departure", placeholder:"出発地" %>
          ～
          <%= location.text_field :arrival2, class:"f-arrival", placeholder:"到着地" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="add-menus-container" id="add-menus">
    <button id="add-button" type="button">＋</button>
  </div>

  <style>
  button{border-radius: 10px; border-style: none; font-weight: bold; font-size: 16px;
        background-color: #a1d8e6; color: #e73562;cursor: pointer; text-align: center;}
  </style>
</div>


<div class="form-set">
  <div class="form">
    費用
  </div>
  <%= schedule.text_field :cost, class:"f-cost" %>
</div>
<div class="form-set">
  <div class="form">
    URL 1
  </div>
  <%= schedule.text_field :url, class:"f-url" %>
</div>
<div class="form-set">
  <div class="form">
    URL 2
  </div>
  <%= schedule.text_field :url2, class:"f-url2" %>
</div>

<div class="form-set">
  <div class="form">
    メモ
  </div>
  <%= schedule.text_area :memo, class:"f-memo" %>
</div>

<div class="form-set">
  <div class="form">
    イメージ
  </div>
  <div class="upload">
    <%= schedule.file_field :image, class:"upload-btn"%>
  </div>
</div>
<div class="required">
  <span>*</span>は必須項目です
</div>

app/views/schedules/edit.html.erb
<div class="tab">
  <div class="format">
    <div class="back">
      <%= link_to image_tag("back.png"), book_schedules_path %>
    </div>

    <%= form_with(model: [@book, @schedule], url: book_schedule_path(@book, @schedule), method: :patch, remote: true,) do |schedule| %>
      <%= render "shared/error_messages", object: schedule.object %>
      <%= render "form", schedule: schedule %>

      <div class="form-set">
        <%= schedule.submit "変更", class:"submit-btn" %>
      </div>
      <div class="destroy">
        <div title="予定を削除">
          <%= link_to image_tag("dustbin.png", class:"destroy-icon"), 
            book_schedule_path(@book, @schedule.id), data: { turbo_method: :delete }, method: :delete %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render "shared/tab" %>
</div>

app/views/schedules/index.html.erb
<div class="tab">
  <div class="schedules">
    <div class="back">
      <%= link_to image_tag("back.png"), root_path %>
    </div>

    <div class="s-index">
      <% grouped_schedules = @schedules.group_by { |schedule| (schedule.departure_time.to_date - @book.start.to_date).to_i + 1 } %>
      <% grouped_schedules.each do |day, schedules_for_day| %>
        <div class="date-group">
          <div class="day">
            DAY <%= day %>
          </div>
          <div class="date">
            <%= schedules_for_day.first.departure_time.strftime("%m/%d (%a)") if schedules_for_day.any? %>
          </div>
        </div>

        <% schedules_for_day.each do |schedule| %>
          <div class="schedule-img">
            <% if schedule.image.attached? %>
              <%= image_tag schedule.image, class: "s-img" %>
            <% end %>
          </div>

          <div class="s-info">
            <div class="s-main">
              <div class="s-icon">
                <%= link_to edit_book_schedule_path(schedule.book, schedule) do %>
                  <% if schedule.icon.is_a?(Icon) && schedule.icon.id != 0 %>
                    <%= image_tag schedule.icon.image, class: "icon" %>
                  <% elsif schedule.icon.is_a?(String) && schedule.icon != "0" %>
                    <%= image_tag schedule.icon, class: "icon" %>
                  <% end %>
                <% end %>
              </div>

              <div class="d-a_time">
                <%= link_to edit_book_schedule_path(schedule.book, schedule) do %>
                  <div class="departure_time">
                    <%= schedule.departure_time&.strftime("%H:%M") %>
                  </div>
                  <div class="arrival_time">
                    <% if schedule.arrival_time.present? %>
                      <%= "-" %><%= schedule.arrival_time&.strftime("%H:%M") %>
                    <% end %>
                  </div>
                <% end %>
              </div>

              <div class="s-sub1">
                <div class="summary">
                  <%= schedule.summary %>
                </div>
                <div class="d-a">
                  <div class="departure">
                    <%= schedule.departure %>
                  </div>
                  <div class="arrival">
                    <% if schedule.arrival.present? %>
                      <%= "～ " %><%= schedule.arrival %>
                    <% end %>
                  </div>
                </div>
              </div>

              <div class="s-sub2">
                <div class="cost">
                  <%= schedule.cost %>
                </div>
                <div class="urls">
                  <% if schedule.url.present? %>
                    <%= link_to image_tag("url.png", class:"url-icon"), 
                      schedule.url, data: {"turbolinks" => false} %>
                  <% end %>
                  <% if schedule.url2.present? %>
                    <%= link_to image_tag("url.png", class:"url-icon"), 
                      schedule.url2, data: {"turbolinks" => false} %>
                  <% end %>
                </div>
              </div>
            </div>

            <%= link_to edit_book_schedule_path(schedule.book, schedule) do %>
              <% if schedule.memo.present? %>
                <div class="memo">
                  <%= schedule.memo %>
                </div>
              <% end %>

              <% schedule.locations.each do |sl| %>
                <div class="s-location">
                  <div class="l-icon">
                    <% if sl.icon_id2.is_a?(Icon) %>
                      <%= image_tag sl.icon.image, class: "icon" %>
                    <% elsif sl.icon_id2.is_a?(String) %>
                      <%= image_tag sl.icon, class: "icon" %>
                    <% end %>
                  </div>

                  <div class="d-a_time">
                    <div class="departure_time">
                      <%= sl.departure_time2&.strftime("%H:%M") %>
                    </div>
                    <div class="arrival_time">
                      <% if sl.arrival_time2.present? %>
                        <%= "-" %><%= sl.arrival_time2&.strftime("%H:%M") %>
                      <% end %>
                    </div>
                  </div>
                  <div class="d-a">
                    <div class="departure">
                      <%= sl.departure2 %>
                    </div>
                    <div class="arrival">
                      <% if sl.arrival2.present? %>
                        <%= "～ " %><%= sl.arrival2 %>
                      <% end %>
                    </div>
                  </div>

                </div>
              <% end %>
            <% end %>

          </div>
        <% end %>
      <% end %>
    </div>

  </div>
  <%= render "shared/tab" %>
</div>

app/views/schedules/new.html.erb
<div class="tab">
  <div class="format">
    <div class="back">
      <%= link_to image_tag("back.png"), book_schedules_path %>
    </div>

    <%= form_with(model: @schedule, url: book_schedules_path(@book), id:"form_id") do |schedule| %>
      <%= render "shared/error_messages", object: schedule.object %>
      <%= render "form", schedule: schedule %>

      <div class="form-set">
        <%= schedule.submit "追加", class:"submit-btn" %>
      </div>
    <% end %>
  </div>
  <%= render "shared/tab" %>
</div>