config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users, only: [:show, :index]
  
  resources :books do
    resources :schedules
    resources :lists
    resource :likes, only: [:create, :destroy]
    collection do
      get "search"
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error-alert">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_tab.html.erb
<% if user_signed_in? && current_user.id == @book.user_id %>
<div class="tab-list">

  <div class="tab-info">
    <div class="tab-book-title">
      <%= link_to @book.title, book_schedules_path(@book), data: {"turbolinks" => false} %>
    </div>
  </div>

  <div class="tab-block">
    <div class="new-schedule">
      <div class="tab-info">
        <%= link_to "＋ 予定", new_book_schedule_path(@book), data: {"turbolinks" => false} %>
      </div>
    </div>
  </div>
  
  <div class="tab-block">
    <div class="new-list">
      <div class="tab-info">
        <%= link_to "＋ リスト", new_book_list_path(@book), data: {"turbolinks" => false} %>
      </div>
    </div>
  </div>

  <div class="tab-block">
    <% @categories.each do |category| %>
      <div class="tab-info">
        <div class="category-list">
          <%= link_to category, book_lists_path(@book, category: category), data: {"turbolinks" => false} %>
        </div>
      </div>
    <% end %>
  </div>

</div>
<% end %>